### ISSUE TITLE
Spike: create-t3-app with turbo-repo

### ISSUE THREAD

**Issue by tatoMa** [taodemy/zoom#1]
Turbo-repo is a must, and may or may not contain an app created with create-t3-app.

**Comment by RedRe4per** [comment]
![t3app1.jpg](https://images.zenhubusercontent.com/63d09da01af10849c2963f1f/14321259-375d-43a3-bceb-560c21c7e945)![t3app2.jpg](https://images.zenhubusercontent.com/63d09da01af10849c2963f1f/2524475e-a82c-4368-addf-3d3cfe4b963f)

**Comment by RedRe4per** [comment]
After testing, I think create-t3-app can be used as a workspace in turbo-repo, and it can run normally.
T3app in turborepo can normally use assets of other workspaces in turborepo, such as UI components. Similarly, prisma and trpc can also run normally.
